# Generated by Django 5.2.1 on 2025-05-26 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(help_text="Enter the author's first name.", max_length=100)),
                ('last_name', models.CharField(help_text="Enter the author's last name.", max_length=100)),
                ('avatar', models.FileField(blank=True, help_text='Upload an avatar image.', null=True, upload_to='authors')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Enter the title of the book.', max_length=200)),
                ('isbn', models.CharField(help_text='Enter the 13-character ISBN number.', max_length=13, unique=True)),
                ('page_count', models.PositiveIntegerField(help_text='Enter the number of pages.')),
                ('is_available', models.BooleanField(default=True)),
                ('author', models.ForeignKey(help_text='Select the author of the book.', on_delete=django.db.models.deletion.PROTECT, to='books.author')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_date', models.DateField(auto_now_add=True, help_text='The date the book was borrowed.')),
                ('return_date', models.DateField(blank=True, help_text='The date the book is expected to be returned.', null=True)),
                ('is_returned', models.BooleanField(default=False, help_text='Has the book been returned?')),
                ('book', models.ForeignKey(help_text='Enter the book to be borrowed.', on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('borrower', models.ForeignKey(help_text="Enter the borrower's username.", on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['-loan_date'],
            },
        ),
    ]
